# Generated by Django 4.0.5 on 2022-06-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='published_date',
        ),
    ]
